### ISSUE TITLE
EMUSC Crashing upon inserting required roms and pressing POWER

### ISSUE THREAD

**Issue by Axis4s** [skjelten/emusc#49] opened 2024-04-08 00:10 UTC
![image](https://github.com/skjelten/emusc/assets/97393974/0c96ad89-e449-44ac-97e7-9b0a735d47b6)
i have my roms, i have my folder, put the roms into the program
![image](https://github.com/skjelten/emusc/assets/97393974/87076a10-9051-4bed-b6b2-f8e8f892b64a)
clicked on the power-on, now it doesn't work, refuses to start.

**Comment by ThatRetroGuy** [comment] 2024-04-08 00:18
it seems to be a general issue with emusc, hopes that get fixed when possible, im very curious with all this progress happened.

**Comment by nickkeane** [comment] 2024-04-08 00:20
Having the same issue

**Comment by Grieferus** [comment] 2024-04-08 00:23
Your ROMs seem to be of SC-55 mk2. Try to use the SC-55 ROMs. Additionally, you should choose Win32 as your audio system.

**Comment by Axis4s** [comment] 2024-04-08 00:26
> Your ROMs seem to be of SC-55 mk2. Try to use the SC-55 ROMs. Additionally, you should choose Win32 as your audio system.

![image](https://github.com/skjelten/emusc/assets/97393974/4f912d0c-4b45-4bf7-8717-f220096a92da)
![image-1](https://github.com/skjelten/emusc/assets/97393974/5ea6e5b5-f56d-4324-a9e2-646463867762)
but the program clearly states MKII roms are ok
also i cant run the program again because it refuses to open, does it save some sort of data to the %appdata% folder?

**Comment by Grieferus** [comment] 2024-04-08 00:32
In the changelog, skjelten stated that it's recommended to use SC-55 samples instead of SC-55 mk2.

**Comment by Grieferus** [comment] 2024-04-08 00:33
As of the config file, I couldn't find one.

**Comment by mmontag** [comment] 2024-04-08 01:30
On Windows, it looks like this config data might be in the Registry. My condolences. https://stackoverflow.com/a/61527355/264970

**Comment by nickkeane** [comment] 2024-04-08 01:36
HKEY_CURRENT_USER\Software\emusc

**Comment by nickkeane** [comment] 2024-04-08 01:44
It's still not working using SC-55 v1.21 control rom and v0.20 PCM roms, even though they are SHA-256 verified.
Clicking Power crashes the app, and then I can't open it again unless I delete the registry keys.

**Comment by skjelten** [comment] 2024-04-08 22:56
Both the SC-55 v1.21 and the SC-55mkII ROMS that you refer to should work just fine to start. The issue with the SC-55mkII ROM is that it sometimes gives completely wrong sample data, but it should not cause a crash.

My guess is that the ROM files are actually not the problem, but either the audio or MIDI configuration is. Could you try to sett audio to _Null_? The MIDI device settings does unfortunately not have a _Null_ option anymore, but try to change it to something else if you can. We should probably add back the Null option for MIDI devices as well so that we can isolate more easily the root cause for any instability.

To save yourself from the hassle of modifying the registry you could try either of these options:
* Go to General preferences and uncheck the option _Power on at startup_
* Start emusc from a command prompt with the parameter **--power-off**: `emusc.exe --power-off`

To quickly start or stop the synth just press space.

Ideally you should also be able to run `emusc.exe --print-config` to easily be able to share your config, but I just tested it and it seems like QT / windows GUI applications do not send any data to the console. Another thing to look at when time permits.

**Comment by nickkeane** [comment] 2024-04-09 01:12
Finally got it to work. I had to switch sound output to Win32 instead of Qt.

Whenever selecting Qt (was defaulted to this) for sound output now, I get an error "Failed to initialize audio system (Qt). Error Message: Raw audio format not supported by backend."

**Comment by skjelten** [comment] 2024-04-09 20:04
Good to hear that you found a fix. I think mmontag had the exact same issue on macOS a few days ago.

I spent quite some time to rewrite QtMultimedia audio output for both version 5 & 6 a while ago, but must clearly have messed up something at the end. We should either fix or disable the Qt output for the next release.

**Comment by skjelten** [comment] 2024-04-13 00:27
Closing this issue as we now have a section about it in the new troubleshooting guide.

https://github.com/skjelten/emusc/wiki/Troubleshooting-Guide

**Closed by skjelten** 2024-04-13 00:27 UTC
