### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by OpenRift412** [skjelten/emusc#40] opened 2024-03-11 20:46 UTC
Just wanted to check in on this project. I noticed that the readme still says that the project is "in an early development stage", although there hasn't really been an update to the readme in at least a year. Does that still remain accurate? If not, what kind of stage would you say the project is in currently?

**Comment by skjelten** [comment] 2024-03-12 22:37
This is a good question that I am not entirely sure how to answer. There has been done a lot of work on this project since the README file was written, but at the same time has my understanding of the remaining parts improved as well. So the project goal, to "reproduce sounds that will make it difficult to notice the difference" from the real hardware, seems to be as distant as ever.

On the positive side I do think that when the initial revision of the reverb system effect is soon committed, emusc will have code to cover all the different areas of audio generation; reading the sound samples, mixing partials, TVA, TVF and pitch envelopes with LFO modulations, chorus and reverb system effects, it handles all MIDI messages affecting audio, including SysEx messages, controller inputs etc. The negative part is that there remains -a lot- of tuning to make all those parts play well together. While for instance the pitch envelope implementation actually sounds really good in certain situations, in other situations it makes the audio plain awful. Same goes for almost all parts of the code.

So, to answer your question, I guess it will be fair to say that the project is about to transition from "an early development stage" to "half the way there". Emusc has come a long way the last year or so, but the SC-55 sound font made by Kitrinx and NewRisingSun is still your best bet for emulating SC-55 audio.

(It is on the forever TODO list to write some kind of status matrix on github wiki so that it would be easier to get a detailed overview of the progress)

**Comment by Grounded0** [comment] 2024-03-12 22:44
I would recommend [4GMGSMT](https://anttipeltola.eu/docs/4GMGSMT.txt) from Creative for anyone trying to mimick Roland SC-55 on a soundfont.

**Comment by zaphod77** [comment] 2024-04-05 23:48
i would not.

it totally ruins tetrinet.mid

i'd suggest his.

https://github.com/trevor0402/SC55Soundfont/releases/download/v1.2b/SC-55.SoundFont.v1.2b.sf2

**Comment by OpenRift412** [comment] 2024-04-06 00:49
> i would not.
> 
> it totally ruins tetrinet.mid
> 
> i'd suggest this.
> 
> https://github.com/trevor0402/SC55Soundfont/releases/download/v1.2b/SC-55.SoundFont.v1.2b.sf2

I'd suggest this:
https://github.com/nukeykt/Nuked-SC55

I know the author behind that soundfont, and I know for a fact he prefers that over his own soundfont.

**Comment by Grounded0** [comment] 2024-04-06 00:59
The main problem i hear with most soundfonts is the amateur hour stuff like instruments attacking at wrong velocities to each other when it should be extremely neutral unless differing note velocity is specified. Not having a balanced soundscape kills it for me. FluidSynth can't fix crap soundfonts.

I think everyone agrees at this point that Nuked-SC55 would be the way to go as of today. Too bad it's currently licensed in a way that prevents GPL projects from adopting it so there needs to be a licence change or a parallel GPL compatible project has to be further developed like the EmuSC.

**Comment by OpenRift412** [comment] 2024-04-06 03:09
> The main problem i hear with most soundfonts is the amateur hour stuff like instruments attacking at wrong velocities to each other when it should be extremely neutral unless differing note velocity is specified. Not having a balanced soundscape kills it for me. FluidSynth can't fix crap soundfonts.
> 
> I think almost everyone agrees at this point that Nuked-SC55 would be the way to go as of today. Too bad it's currently licensed in a way that prevents GPL projects from adopting it so there needs to be a licence change, dual licensing or a parallel GPL compatible project has to be further developed like the EmuSC.

I think NukeYKT is open to changing to a different license at some point, just not anytime soon.

**Closed** 2024-04-13 01:18 UTC
